version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: SharpCompress
    versions:
    - 0.27.1
    - 0.28.0
    - 0.28.1
