//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class translations {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ExtremeStudio.Translations.translations", typeof(translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Name: .
        /// </summary>
        public static string AutoCompleteItemEx_New_FunctionName {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters :.
        /// </summary>
        public static string AutoCompleteItemEx_New_Parameters {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PawnDoc Help: .
        /// </summary>
        public static string AutoCompleteItemEx_New_PawnDocHelp {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_PawnDocHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks: .
        /// </summary>
        public static string AutoCompleteItemEx_New_Remarks {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns: .
        /// </summary>
        public static string AutoCompleteItemEx_New_Returns {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Tag: .
        /// </summary>
        public static string AutoCompleteItemEx_New_ReturnTag {
            get {
                return ResourceManager.GetString("AutoCompleteItemEx_New_ReturnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains un-saved content, Would you like to save it ?.
        /// </summary>
        public static string EditorDock_EditorDock_FormClosing_FileContainsUnSavedContent {
            get {
                return ResourceManager.GetString("EditorDock_EditorDock_FormClosing_FileContainsUnSavedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle..
        /// </summary>
        public static string EditorDock_RefreshWorker_RunWorkerCompleted_Idle {
            get {
                return ResourceManager.GetString("EditorDock_RefreshWorker_RunWorkerCompleted_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include `{0}` is not found, Please make sure it exists..
        /// </summary>
        public static string EditorDock_RefreshWorker_RunWorkerCompleted_IncludeNotFoundError {
            get {
                return ResourceManager.GetString("EditorDock_RefreshWorker_RunWorkerCompleted_IncludeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Code..
        /// </summary>
        public static string EditorDock_scintilla_TextChangedDelayed_ParsingCode {
            get {
                return ResourceManager.GetString("EditorDock_scintilla_TextChangedDelayed_ParsingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Plugin.
        /// </summary>
        public static string EsPluginsForm_PluginList_Click_InstallPlugin {
            get {
                return ResourceManager.GetString("EsPluginsForm_PluginList_Click_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReInstall Plugin.
        /// </summary>
        public static string EsPluginsForm_PluginList_Click_ReInstallPlugin {
            get {
                return ResourceManager.GetString("EsPluginsForm_PluginList_Click_ReInstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your value, It seems to be wrong..
        /// </summary>
        public static string GotoForm_GoBtn_Click_CheckYourValues {
            get {
                return ResourceManager.GetString("GotoForm_GoBtn_Click_CheckYourValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: .
        /// </summary>
        public static string GotoForm_linenumberRadio_CheckedChanged_CurrentLabel {
            get {
                return ResourceManager.GetString("GotoForm_linenumberRadio_CheckedChanged_CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number: .
        /// </summary>
        public static string GotoForm_linenumberRadio_CheckedChanged_LineNumberLabel {
            get {
                return ResourceManager.GetString("GotoForm_linenumberRadio_CheckedChanged_LineNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum: .
        /// </summary>
        public static string GotoForm_linenumberRadio_CheckedChanged_MaximumLabel {
            get {
                return ResourceManager.GetString("GotoForm_linenumberRadio_CheckedChanged_MaximumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        public static string GotoForm_positionRadio_CheckedChanged_PositionLabel {
            get {
                return ResourceManager.GetString("GotoForm_positionRadio_CheckedChanged_PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include &apos;{0}&apos; has been successfully installed..
        /// </summary>
        public static string IncludesForm_Button1_Click_IncludeInstalled {
            get {
                return ResourceManager.GetString("IncludesForm_Button1_Click_IncludeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include can&apos;t be found in the cache..
        /// </summary>
        public static string IncludesForm_Button1_Click_IncludeNotFoundCache {
            get {
                return ResourceManager.GetString("IncludesForm_Button1_Click_IncludeNotFoundCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include is cached, No description is available..
        /// </summary>
        public static string IncludesForm_IncludesForm_Load_IncludeCached {
            get {
                return ResourceManager.GetString("IncludesForm_IncludesForm_Load_IncludeCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This include needs the {0} plugin to work..
        /// </summary>
        public static string IncludesForm_includesList_SelectedIndexChanged_IncludeNeedsPlugin {
            get {
                return ResourceManager.GetString("IncludesForm_includesList_SelectedIndexChanged_IncludeNeedsPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Include.
        /// </summary>
        public static string IncludesForm_includesList_SelectedIndexChanged_InstallInclude {
            get {
                return ResourceManager.GetString("IncludesForm_includesList_SelectedIndexChanged_InstallInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Include.
        /// </summary>
        public static string IncludesForm_includesList_SelectedIndexChanged_ReinstallInclude {
            get {
                return ResourceManager.GetString("IncludesForm_includesList_SelectedIndexChanged_ReinstallInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file pawncc.exe hasn&apos;t been found at the path.
        /// </summary>
        public static string MainForm_CompilerWorker_DoWork_PawnccNotFound {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_DoWork_PawnccNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify its there..
        /// </summary>
        public static string MainForm_CompilerWorker_DoWork_VerifyPawnccIsThere {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_DoWork_VerifyPawnccIsThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save all files ?.
        /// </summary>
        public static string MainForm_CompilerWorker_DoWork_WouldYouLikeToSaveFiles {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_DoWork_WouldYouLikeToSaveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling....
        /// </summary>
        public static string MainForm_CompilerWorker_ProgressChanged_Compiling {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_ProgressChanged_Compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling finished sucessfully with no errors/warnings..
        /// </summary>
        public static string MainForm_CompilerWorker_ProgressChanged_CompilingDoneWithNoErrorsWarnings {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_ProgressChanged_CompilingDoneWithNoErrorsWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling finished successfully but there are warning(s)..
        /// </summary>
        public static string MainForm_CompilerWorker_ProgressChanged_CompilingDoneWithWarnings {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_ProgressChanged_CompilingDoneWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling failed with errors/warnings..
        /// </summary>
        public static string MainForm_CompilerWorker_ProgressChanged_CompilingFailedWithErrors {
            get {
                return ResourceManager.GetString("MainForm_CompilerWorker_ProgressChanged_CompilingFailedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until the current compilation or parsing process is finished..
        /// </summary>
        public static string MainForm_compileScriptBtn_Click_WaitForCompile {
            get {
                return ResourceManager.GetString("MainForm_compileScriptBtn_Click_WaitForCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter any details..
        /// </summary>
        public static string ObjectExplorerDockItems_addBtn_Click_PleaseEnterDetials {
            get {
                return ResourceManager.GetString("ObjectExplorerDockItems_addBtn_Click_PleaseEnterDetials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ?.
        /// </summary>
        public static string ObjectExplorerDockItems_deleteBtn_Click_YouWantDelete {
            get {
                return ResourceManager.GetString("ObjectExplorerDockItems_deleteBtn_Click_YouWantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin can&apos;t be found in the cache..
        /// </summary>
        public static string PluginsForm_Button1_Click_PluginCantBeFoundInCache {
            get {
                return ResourceManager.GetString("PluginsForm_Button1_Click_PluginCantBeFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin &apos;{0}&apos; has been successfully installed..
        /// </summary>
        public static string PluginsForm_Button1_Click_PluginInstalled {
            get {
                return ResourceManager.GetString("PluginsForm_Button1_Click_PluginInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to server.cfg.
        /// </summary>
        public static string PluginsForm_includesList_SelectedIndexChanged_AddToServerCfg {
            get {
                return ResourceManager.GetString("PluginsForm_includesList_SelectedIndexChanged_AddToServerCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Plugin.
        /// </summary>
        public static string PluginsForm_includesList_SelectedIndexChanged_InstallPlugin {
            get {
                return ResourceManager.GetString("PluginsForm_includesList_SelectedIndexChanged_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Plugin.
        /// </summary>
        public static string PluginsForm_includesList_SelectedIndexChanged_ReinstallPlugin {
            get {
                return ResourceManager.GetString("PluginsForm_includesList_SelectedIndexChanged_ReinstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from server.cfg.
        /// </summary>
        public static string PluginsForm_includesList_SelectedIndexChanged_RemoveFromServerCfg {
            get {
                return ResourceManager.GetString("PluginsForm_includesList_SelectedIndexChanged_RemoveFromServerCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin needs the {0} include to work..
        /// </summary>
        public static string PluginsForm_includesList_SelectedIndexChanged_ThisPluginNeedsTheIncludeToWork {
            get {
                return ResourceManager.GetString("PluginsForm_includesList_SelectedIndexChanged_ThisPluginNeedsTheIncludeToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin is cached, No description is available..
        /// </summary>
        public static string PluginsForm_PluginsForm_Load_PluginCached {
            get {
                return ResourceManager.GetString("PluginsForm_PluginsForm_Load_PluginCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filetype is not supported to be veiwed by ExtremeStudio so it will be opened normally..
        /// </summary>
        public static string ProjExplorerDock_filesList_FileSelected_FileNotSupported {
            get {
                return ResourceManager.GetString("ProjExplorerDock_filesList_FileSelected_FileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the directory..
        /// </summary>
        public static string ProjExplorerDock_NewDirectoryToolStripMenuItem_Click_PleaseEnterNameForDir {
            get {
                return ResourceManager.GetString("ProjExplorerDock_NewDirectoryToolStripMenuItem_Click_PleaseEnterNameForDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the file.
        ///
        ///NOTE: INCLUDE THE EXTENSION!.
        /// </summary>
        public static string ProjExplorerDock_NewFileToolStripMenuItem_Click_PleaseEnterNameForFile {
            get {
                return ResourceManager.GetString("ProjExplorerDock_NewFileToolStripMenuItem_Click_PleaseEnterNameForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name..
        /// </summary>
        public static string ProjExplorerDock_RenameToolStripMenuItem_Click_EnterNewNameTitle {
            get {
                return ResourceManager.GetString("ProjExplorerDock_RenameToolStripMenuItem_Click_EnterNewNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name for the file.
        ///
        ///NOTE: INCLUDE THE EXTENSION!.
        /// </summary>
        public static string ProjExplorerDock_RenameToolStripMenuItem_Click_PleaseEnterNameForFile {
            get {
                return ResourceManager.GetString("ProjExplorerDock_RenameToolStripMenuItem_Click_PleaseEnterNameForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name for the directory..
        /// </summary>
        public static string ProjExplorerDock_RenameToolStripMenuItem_Click_PleaseEnterNewDirName {
            get {
                return ResourceManager.GetString("ProjExplorerDock_RenameToolStripMenuItem_Click_PleaseEnterNewDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items replaced are: .
        /// </summary>
        public static string SearchReplaceForm_replaceReplaceAllBtn_Click_NumberItemsReplaced {
            get {
                return ResourceManager.GetString("SearchReplaceForm_replaceReplaceAllBtn_Click_NumberItemsReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached End Of Document..
        /// </summary>
        public static string SearchReplaceForm_SearchAndMark_ReachedEndDocument {
            get {
                return ResourceManager.GetString("SearchReplaceForm_SearchAndMark_ReachedEndDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items found are: .
        /// </summary>
        public static string SearchReplaceForm_searchCountBtn_Click_NumberItemsFound {
            get {
                return ResourceManager.GetString("SearchReplaceForm_searchCountBtn_Click_NumberItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CTRL+SHIFT+N and CTRL+SHIFT+B to fast-travel in between the finds..
        /// </summary>
        public static string SearchReplaceForm_searchFindAllBtn_Click_UseKeysForTravel {
            get {
                return ResourceManager.GetString("SearchReplaceForm_searchFindAllBtn_Click_UseKeysForTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Successfully!.
        /// </summary>
        public static string SettingsForm_exportBtn_Click_ExporteSuccess {
            get {
                return ResourceManager.GetString("SettingsForm_exportBtn_Click_ExporteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target..
        /// </summary>
        public static string SettingsForm_exportBtn_Click_OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("SettingsForm_exportBtn_Click_OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source..
        /// </summary>
        public static string SettingsForm_importBtn_Click_OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("SettingsForm_importBtn_Click_OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings. [GLOBAL].
        /// </summary>
        public static string SettingsForm_IsGlobal_SettingsGLOBAL {
            get {
                return ResourceManager.GetString("SettingsForm_IsGlobal_SettingsGLOBAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings. [PROJECT].
        /// </summary>
        public static string SettingsForm_IsGlobal_SettingsPROJECT {
            get {
                return ResourceManager.GetString("SettingsForm_IsGlobal_SettingsPROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset to default settings ?.
        /// </summary>
        public static string SettingsForm_resetBtn_Click_ResetDefaultSettings {
            get {
                return ResourceManager.GetString("SettingsForm_resetBtn_Click_ResetDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization settings have been deleted sucessfully, please restart application and the language dialog will show..
        /// </summary>
        public static string SettingsForm_ResetLangBtn_Click_LocalizationSettingsDeleted {
            get {
                return ResourceManager.GetString("SettingsForm_ResetLangBtn_Click_LocalizationSettingsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Would you like to continue ?.
        /// </summary>
        public static string StartupForm_Button1_Click_WouldYouLikeToContinue {
            get {
                return ResourceManager.GetString("StartupForm_Button1_Click_WouldYouLikeToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That directory doesn&apos;t exist or there is a project with that name already there..
        /// </summary>
        public static string StartupForm_CreateProjectBtn_Click_DirError {
            get {
                return ResourceManager.GetString("StartupForm_CreateProjectBtn_Click_DirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name..
        /// </summary>
        public static string StartupForm_CreateProjectBtn_Click_InvalidName {
            get {
                return ResourceManager.GetString("StartupForm_CreateProjectBtn_Click_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SAMP Folder.. 
        ///Must contain the pawno folder, gamemodes folder, plugins folder, all executables and the server config..
        /// </summary>
        public static string StartupForm_CreateProjectBtn_Click_InvalidSampFolder {
            get {
                return ResourceManager.GetString("StartupForm_CreateProjectBtn_Click_InvalidSampFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected a SAMP version to use..
        /// </summary>
        public static string StartupForm_CreateProjectBtn_Click_NoSampSelected {
            get {
                return ResourceManager.GetString("StartupForm_CreateProjectBtn_Click_NoSampSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: That folder isn&apos;t a valid ExtremeStudio project. Make sure you haven&apos;t deleted or modified any file manually..
        /// </summary>
        public static string StartupForm_pathTextBox_TextChanged_InvalidESPrj {
            get {
                return ResourceManager.GetString("StartupForm_pathTextBox_TextChanged_InvalidESPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StartupForm_pathTextBox_TextChanged_None {
            get {
                return ResourceManager.GetString("StartupForm_pathTextBox_TextChanged_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project version is newer then ExtremeStudio&apos;s version, Please download latest ExtremeStudio package..
        /// </summary>
        public static string StartupForm_pathTextBox_TextChanged_ProjectVersionNewer {
            get {
                return ResourceManager.GetString("StartupForm_pathTextBox_TextChanged_ProjectVersionNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project older then ExtremeStudio, Conversion will be done however it may bug with older versions so its recommended to not try..
        /// </summary>
        public static string StartupForm_pathTextBox_TextChanged_ProjectVersionOlder {
            get {
                return ResourceManager.GetString("StartupForm_pathTextBox_TextChanged_ProjectVersionOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project version is the same as ExtremeStudio&apos;s version, No converion is needed..
        /// </summary>
        public static string StartupForm_pathTextBox_TextChanged_ProjectVersionSame {
            get {
                return ResourceManager.GetString("StartupForm_pathTextBox_TextChanged_ProjectVersionSame", resourceCulture);
            }
        }
    }
}
