'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ExtremeStudio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property correct_projexplorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correct_projexplorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        '''&lt;allStuffClass&gt;
        '''  &lt;defaultColor&gt;
        '''    &lt;R&gt;0&lt;/R&gt;
        '''    &lt;G&gt;0&lt;/G&gt;
        '''    &lt;B&gt;0&lt;/B&gt;
        '''    &lt;A&gt;255&lt;/A&gt;
        '''  &lt;/defaultColor&gt;
        '''  &lt;pawnDocColor&gt;
        '''    &lt;R&gt;225&lt;/R&gt;
        '''    &lt;G&gt;0&lt;/G&gt;
        '''    &lt;B&gt;0&lt;/B&gt;
        '''    &lt;A&gt;255&lt;/A&gt;
        '''  &lt;/pawnDocColor&gt;
        '''  &lt;pawnColor&gt;
        '''    &lt;R&gt;0&lt;/R&gt;
        '''    &lt;G&gt;0&lt;/G&gt;
        '''    &lt;B&gt;225&lt;/B&gt;
        '''    &lt;A&gt;255&lt;/A&gt;
        '''  &lt;/pawnColor&gt;
        '''  &lt;definesColor&gt;
        '''    &lt;R&gt;199&lt;/R&gt;
        '''    &lt;G&gt;21&lt;/G&gt;
        '''    &lt;B&gt;133&lt;/B&gt;
        '''    &lt;A&gt;255&lt;/A&gt;
        '''  &lt;/definesColor&gt;
        '''  &lt;operatorColor&gt;
        '''    &lt;R&gt;128&lt;/R&gt;
        '''    &lt;G&gt;0&lt;/G&gt;
        '''    &lt;B&gt;128&lt;/B&gt;
        '''    &lt;A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property defaultThemeInfo() As String
            Get
                Return ResourceManager.GetString("defaultThemeInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirs_projexplorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirs_projexplorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_projexplorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_projexplorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property includes_icon_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("includes_icon_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_file_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_file_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // This is a comment
        '''// uncomment the line below if you want to write a filterscript
        '''//#define FILTERSCRIPT
        '''
        '''#include &lt;a_samp&gt;
        '''
        '''#if defined FILTERSCRIPT
        '''
        '''public OnFilterScriptInit()
        '''{
        '''	print(&quot;\n--------------------------------------&quot;);
        '''	print(&quot; Blank Filterscript by your name here&quot;);
        '''	print(&quot;--------------------------------------\n&quot;);
        '''	return 1;
        '''}
        '''
        '''public OnFilterScriptExit()
        '''{
        '''	return 1;
        '''}
        '''
        '''#else
        '''
        '''main()
        '''{
        '''	print(&quot;\n----------------------------------&quot;);
        '''	print(&quot; Blank Gamemode by  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property newfileTemplate() As String
            Get
                Return ResourceManager.GetString("newfileTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plugins_icon_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugins_icon_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_file_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_file_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saveall_file_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveall_file_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_icon_toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_icon_toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SQLiteInterop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLiteInterop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
