//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ExtremeStudio.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ExtremeStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap correct_projexplorer {
            get {
                object obj = ResourceManager.GetObject("correct_projexplorer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Colors&quot;: {
        ///    &quot;SDefault&quot;: {
        ///      &quot;Font&quot;: &quot;Courier New, 10pt&quot;,
        ///      &quot;ForeColor&quot;: &quot;Black&quot;,
        ///      &quot;BackColor&quot;: &quot;Transparent&quot;
        ///    },
        ///    &quot;SInteger&quot;: {
        ///      &quot;Font&quot;: null,
        ///      &quot;ForeColor&quot;: &quot;Purple&quot;,
        ///      &quot;BackColor&quot;: &quot;Transparent&quot;
        ///    },
        ///    &quot;SString&quot;: {
        ///      &quot;Font&quot;: null,
        ///      &quot;ForeColor&quot;: &quot;Firebrick&quot;,
        ///      &quot;BackColor&quot;: &quot;Transparent&quot;
        ///    },
        ///    &quot;SSymbols&quot;: {
        ///      &quot;Font&quot;: null,
        ///      &quot;ForeColor&quot;: &quot;Purple&quot;,
        ///      &quot;BackColor&quot;: &quot;Transparent&quot;
        ///    },
        ///    &quot;SSlComments&quot;: {
        ///      &quot;F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultThemeInfo {
            get {
                return ResourceManager.GetString("defaultThemeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap dirs_projexplorer {
            get {
                object obj = ResourceManager.GetObject("dirs_projexplorer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.162884333821376&quot; DockRightPortion=&quot;0.181918008784773&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.306198347107438&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;1&quot;&gt;
        ///  &lt;Contents Count=&quot;3&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;ExtremeStudio.ProjExplorerDock&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;Fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docksInfo {
            get {
                return ResourceManager.GetString("docksInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap file_projexplorer {
            get {
                object obj = ResourceManager.GetObject("file_projexplorer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This is a comment
        ///// uncomment the line below if you want to write a filterscript
        /////#define FILTERSCRIPT
        ///
        ///#include &lt;a_samp&gt;
        ///
        ///#if defined FILTERSCRIPT
        ///
        ///public OnFilterScriptInit()
        ///{
        ///	print(&quot;\n--------------------------------------&quot;);
        ///	print(&quot; Blank Filterscript by your name here&quot;);
        ///	print(&quot;--------------------------------------\n&quot;);
        ///	return 1;
        ///}
        ///
        ///public OnFilterScriptExit()
        ///{
        ///	return 1;
        ///}
        ///
        ///#else
        ///
        ///main()
        ///{
        ///	print(&quot;\n----------------------------------&quot;);
        ///	print(&quot; Blank Gamemode by  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newfileTemplate {
            get {
                return ResourceManager.GetString("newfileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_addIndent {
            get {
                object obj = ResourceManager.GetObject("ribbon_addIndent", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_autoIndent {
            get {
                object obj = ResourceManager.GetObject("ribbon_autoIndent", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_closeProject {
            get {
                object obj = ResourceManager.GetObject("ribbon_closeProject", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_compile {
            get {
                object obj = ResourceManager.GetObject("ribbon_compile", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_copy {
            get {
                object obj = ResourceManager.GetObject("ribbon_copy", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_cut {
            get {
                object obj = ResourceManager.GetObject("ribbon_cut", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_errors {
            get {
                object obj = ResourceManager.GetObject("ribbon_errors", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_esPlugins {
            get {
                object obj = ResourceManager.GetObject("ribbon_esPlugins", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_goto {
            get {
                object obj = ResourceManager.GetObject("ribbon_goto", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_includes {
            get {
                object obj = ResourceManager.GetObject("ribbon_includes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_newFile {
            get {
                object obj = ResourceManager.GetObject("ribbon_newFile", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_objectExplrer {
            get {
                object obj = ResourceManager.GetObject("ribbon_objectExplrer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_paste {
            get {
                object obj = ResourceManager.GetObject("ribbon_paste", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_plugins {
            get {
                object obj = ResourceManager.GetObject("ribbon_plugins", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_removeIndent {
            get {
                object obj = ResourceManager.GetObject("ribbon_removeIndent", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_saveFile {
            get {
                object obj = ResourceManager.GetObject("ribbon_saveFile", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_saveFileAll {
            get {
                object obj = ResourceManager.GetObject("ribbon_saveFileAll", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_search {
            get {
                object obj = ResourceManager.GetObject("ribbon_search", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_searchAndReplace {
            get {
                object obj = ResourceManager.GetObject("ribbon_searchAndReplace", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ribbon_settings {
            get {
                object obj = ResourceManager.GetObject("ribbon_settings", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SQLite_Interop {
            get {
                object obj = ResourceManager.GetObject("SQLite_Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap warning_icon {
            get {
                object obj = ResourceManager.GetObject("warning_icon", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
