//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtremeStudio.Core.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StartupView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartupView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtremeStudio.Core.Translations.StartupView", typeof(StartupView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Project.
        /// </summary>
        public static string LoadProject_Header {
            get {
                return ResourceManager.GetString("LoadProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LoadProject_NoneLabel {
            get {
                return ResourceManager.GetString("LoadProject_NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Directory: .
        /// </summary>
        public static string LoadProject_ProjectDirLabel {
            get {
                return ResourceManager.GetString("LoadProject_ProjectDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name: .
        /// </summary>
        public static string LoadProject_ProjectNameLabel {
            get {
                return ResourceManager.GetString("LoadProject_ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Version: .
        /// </summary>
        public static string LoadProject_ProjectVersionLabel {
            get {
                return ResourceManager.GetString("LoadProject_ProjectVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from pre-existing files..
        /// </summary>
        public static string NewProject_CreateFromPreExisting {
            get {
                return ResourceManager.GetString("NewProject_CreateFromPreExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string NewProject_CreateProject {
            get {
                return ResourceManager.GetString("NewProject_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject_Header {
            get {
                return ResourceManager.GetString("NewProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location: .
        /// </summary>
        public static string NewProject_ProjectLocationlabel {
            get {
                return ResourceManager.GetString("NewProject_ProjectLocationlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name: .
        /// </summary>
        public static string NewProject_ProjectNameLabel {
            get {
                return ResourceManager.GetString("NewProject_ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMP Version: .
        /// </summary>
        public static string NewProject_SAMPVersionLabel {
            get {
                return ResourceManager.GetString("NewProject_SAMPVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string Recent_DeleteSelectedButton {
            get {
                return ResourceManager.GetString("Recent_DeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent_Header {
            get {
                return ResourceManager.GetString("Recent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Selected.
        /// </summary>
        public static string Recent_LoadSelectedButton {
            get {
                return ResourceManager.GetString("Recent_LoadSelectedButton", resourceCulture);
            }
        }
    }
}
